import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Visual TenX || Best Designing and Web Development Angency In Karnal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
